sudo: false
dist: trusty
language: php

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2

branches:
  only:
    - master
    - develop

before_script:
  - composer install

script:
  - make unit-coverage

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
