sudo: false
dist: trusty
language: php

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2

branches:
  only:
    - master

before_script:
  - composer install

script:
  - vendor/bin/phpunit